const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path'),{webcrypto}=require('node:crypto');
const html=require('./helpers/load-app.cjs')(),ctx=vm.createContext({crypto:webcrypto,TextEncoder});
for(const id of ['', 'resqnet-core','resqnet-audit','resqnet-layout'])vm.runInContext(html.match(id?new RegExp(`<script id="${id}">([\\s\\S]*?)<\\/script>`):/<script>([\s\S]*?)<\/script>/)[1],ctx);
const {C,A,L,config,scene}=vm.runInContext('({C:ResqnetCore,A:ResqnetAudit,L:ResqnetLayout,config:CONFIG,scene:SCENE})',ctx);
const near=(a,b)=>assert(Math.abs(a-b)<1e-8,`${a} != ${b}`);let checks=0,maxDistance=0,frames=0;
function fixture(initialPartial=false){const nodes={O:[0,0],B:[10,0],C:[20,0],I:[30,0],D:[10,10]};const s=C.createState({patients:{fracture:1},fleet:{count:1,capacity:2,bases:['O']},incident:{node:'I'},hospitals:[{id:'H',node:'O',stock:{icu:0,blood:0,vent:0,beds:2}}],edges:[['O','B'],['B','C'],['C','I'],['B','D'],['D','I']]},nodes),an=C.createAnimation(s,{speed:10,dwell:.2});if(initialPartial)s.roads[0].blockage=1;C.startSimulation(s);C.advanceAnimation(an,0);C.advanceAnimation(an,.5);return {s,an,a:s.ambulances[0],v:an.vehicles.A1};}
const road=(s,x,y)=>s.roads.find(r=>r.from===x&&r.to===y||r.from===y&&r.to===x);
function block(f,x,y,n=2){C.setRoadBlockage(f.an,road(f.s,x,y).id,n);}
function distance(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],d=dx*dx+dy*dy,t=d?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/d)):0;return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);}
function verifyPosition(f){const items=L.items(f.an),boxes=L.place(items);for(let i=0;i<items.length;i++){const d=distance(boxes[i].point,items[i].from,items[i].to);assert(d<=6+1e-8);maxDistance=Math.max(maxDistance,d);near(boxes[i].core[0],f.an.vehicles[items[i].id].position[0]);near(boxes[i].core[1],f.an.vehicles[items[i].id].position[1]);}frames++;}
function advance(f,dt){const before=[...f.v.position];C.advanceAnimation(f.an,dt);assert(Math.hypot(f.v.position[0]-before[0],f.v.position[1]-before[1])<=10*dt+1e-8,'physical jump');verifyPosition(f);}
function shortest(s,start,end){const cost=Object.fromEntries(Object.keys(s.nodes).map(n=>[n,Infinity])),todo=new Set(Object.keys(s.nodes));cost[start]=0;while(todo.size){const u=[...todo].sort((a,b)=>cost[a]-cost[b])[0];todo.delete(u);for(const r of s.roads){if(r.blockage===2)continue;const v=r.from===u?r.to:r.to===u?r.from:null;if(v)cost[v]=Math.min(cost[v],cost[u]+r.baseDistance*(r.blockage===1?3:1));}}return cost[end];}
async function test(name,fn){await fn();checks++;console.log('PASS '+name);}
(async()=>{
await test('future partial/full blockage: optimal detour from exact mid-edge position',()=>{for(const n of [1,2]){const f=fixture();block(f,'B','C',n);assert.equal(f.a.currentPath.join('>'),'O>B>D>I');near(f.v.position[0],5);const e=f.s.events.filter(e=>e.kind==='reroute').at(-1);near(e.start.progress,.5);near(e.cost,5+shortest(f.s,'B','I'));assert.equal(e.oldPath.join('>'),'O>B>C>I');assert.equal(e.newPath.join('>'),'O>B>D>I');for(let i=0;i<100&&f.a.status==='to_incident';i++)advance(f,.05);assert.equal(f.a.status,'loading');console.log(`  blockage=${n}; route=O>B>D>I; optimal cost=${e.cost.toFixed(6)}`);}});
await test('currently crossed edge completes before reroute, including long-frame boundary',()=>{const f=fixture();block(f,'O','B');assert(f.v.pendingReroute);assert.equal(f.s.events.filter(e=>e.kind==='reroute').length,0);advance(f,.25);near(f.v.position[0],7.5);assert.equal(f.s.events.filter(e=>e.kind==='reroute').length,0);advance(f,5);near(f.v.position[0],10);assert.equal(f.a.currentPath.join('>'),'B>C>I');assert.equal(f.s.events.filter(e=>e.kind==='reroute').length,1);advance(f,.1);near(f.v.position[0],11);});
await test('all onward routes blocked: stuck holds exact midpoint; unblocking retries next tick',()=>{const f=fixture();block(f,'B','C');block(f,'B','D');assert.equal(f.a.status,'stuck');near(f.v.position[0],5);for(let i=0;i<10;i++)advance(f,.1);near(f.v.position[0],5);block(f,'B','C',0);assert.equal(f.a.status,'stuck');advance(f,.1);assert.equal(f.a.status,'to_incident');near(f.v.position[0],5);advance(f,.1);near(f.v.position[0],6);});
await test('current-edge deferral uses latest graph and becomes stuck at next node',()=>{const f=fixture();block(f,'O','B');block(f,'B','C');block(f,'B','D');advance(f,.5);near(f.v.position[0],10);assert.equal(f.a.status,'stuck');assert.equal(f.s.events.filter(e=>e.kind==='reroute').length,1);});
await test('unrelated road change does not reroute active path',()=>{const f=fixture();block(f,'B','D');assert.equal(f.s.events.filter(e=>e.kind==='reroute').length,0);});
await test('loaded ambulance preserves cargo/reservations through blocked route and recovery',()=>{const f=fixture();while(f.a.status!=='to_hospital')advance(f,.1);advance(f,.3);const reservation=JSON.stringify(f.a.hospitalReservation),cargo=f.a.cargo[0].id;block(f,'O','B');assert.equal(f.a.status,'stuck');assert.equal(JSON.stringify(f.a.hospitalReservation),reservation);assert.equal(f.a.cargo[0].id,cargo);block(f,'O','B',0);advance(f,.1);for(let i=0;i<200&&f.s.status==='running';i++)advance(f,.05);assert.equal(f.s.deliveredCount,1);assert.equal(f.s.hospitals[0].reserved.beds,0);});
await test('reroutes with old/new paths are hash chained; corruption still reports both hashes',async()=>{const f=fixture(),log=A.create(),o=A.observer(f.s,log);o.drain();block(f,'B','C');o.drain();const entries=await log.export(),e=entries.find(e=>e.data.kind==='reroute');assert(e.data.text.includes('Old: O → B → C → I'));assert(e.data.text.includes('New: O → B → D → I'));assert((await log.verify()).ok);await log.corrupt(e.data.id);const r=await log.verify();assert.equal(r.index,e.data.id);assert.equal(r.ok,false);assert.notEqual(r.recordedHash,r.recomputedHash);console.log(`  ${entries.length} entries verified; altered reroute detected at entry ${r.index}`);});
await test('mid-edge optimal cost preserves the partial-road entry penalty',()=>{const f=fixture(true);block(f,'B','C');const e=f.s.events.filter(e=>e.kind==='reroute').at(-1);near(e.cost,15+shortest(f.s,'B','I'));near(f.v.position[0],5);});
await test('four-ambulance disrupted run: continuous core positions, capped rendering, completion and valid chain',async()=>{
 const s=C.createState(config,scene.nodes),an=C.createAnimation(s,{dwell:12}),log=A.create(),o=A.observer(s,log);C.startSimulation(s);let n=0,max=0;
 while(s.status==='running'&&n<12000){
  const previous=Object.fromEntries(Object.entries(an.vehicles).map(([id,v])=>[id,[...v.position]]));
  if(n===200||n===400||n===600||n===800){for(const r of s.roads)C.setRoadBlockage(an,r.id,n===400?2:n===600?0:n===200?(r.id==='R7'?1:r.blockage):(r.id==='R2'?2:r.blockage));}
  if(n===1000)for(const r of s.roads)C.setRoadBlockage(an,r.id,0);
  o.advance(an,1/60);const items=L.items(an),boxes=L.place(items);
  for(let i=0;i<items.length;i++){const a=items[i],p=previous[a.id],q=an.vehicles[a.id].position;assert(Math.hypot(q[0]-p[0],q[1]-p[1])<=70/60+1e-8,'reroute teleported');const d=distance(boxes[i].point,a.from,a.to);assert(d<=6+1e-8);max=Math.max(max,d);near(boxes[i].core[0],q[0]);near(boxes[i].core[1],q[1]);}
  n++;
 }
 assert.equal(s.status,'resolved');assert.equal(s.deliveredCount,13);assert((await log.verify()).ok);const entries=await log.export();assert(entries.some(e=>e.data.kind==='reroute'));console.log(`  full disrupted run: ${n} frames, ${n*4} positions; max distance=${max.toFixed(9)}px; 13 delivered; ${entries.length} entries verified`);
});
console.log(`${checks}/${checks} Phase 5 tests passed; ${frames} disrupted frame/position checks; maximum segment distance=${maxDistance.toFixed(9)}px; zero violations.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
