const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path'),{webcrypto,createHash}=require('node:crypto');
const html=require('./helpers/load-app.cjs')(),ctx=vm.createContext({crypto:webcrypto,TextEncoder});
for(const id of ['', 'resqnet-core','resqnet-audit','resqnet-layout'])vm.runInContext(html.match(id?new RegExp(`<script id="${id}">([\\s\\S]*?)<\\/script>`):/<script>([\s\S]*?)<\/script>/)[1],ctx);
const {C,A,L,config,scene}=vm.runInContext('({C:ResqnetCore,A:ResqnetAudit,L:ResqnetLayout,config:CONFIG,scene:SCENE})',ctx);
let passed=0;async function test(name,f){await f();console.log('PASS '+name);passed++;}
(async()=>{
await test('queued entries retain order; SHA-256 matches independent Node hash',async()=>{const log=A.create();const source={simTime:'00:00',kind:'dispatch',text:'A1 claimed P01'};const p=log.append(source);source.text='changed outside log';await Promise.all([p,...Array.from({length:9},(_,i)=>log.append({simTime:'00:01',kind:'delivery',text:'event '+i}))]);const entries=await log.export();assert.equal(entries.length,10);assert.equal(entries[0].data.text,'A1 claimed P01');for(const e of entries)assert.equal(e.hash,createHash('sha256').update(A.canonical(e.data)+e.previousHash).digest('hex'));assert((await log.verify()).ok);});
await test('tampered entry is detected and located exactly at entry 2',async()=>{const log=A.create();for(let i=0;i<4;i++)await log.append({simTime:'00:00',kind:'snapshot',text:'snapshot '+i});assert((await log.verify()).ok);await log.corrupt(2);const r=await log.verify();assert.equal(r.ok,false);assert.equal(r.index,2);console.log('  untouched: 4 verified; altered: FAIL at entry 2');});
await test('modified hash, broken link, reorder and truncation are detected',async()=>{const log=A.create();for(let i=0;i<3;i++)await log.append({text:'e'+i});const entries=await log.export(),head=entries.at(-1).hash;for(const alter of [e=>e[0].hash='bad',e=>e[1].previousHash='bad',e=>[e[0],e[1]]=[e[1],e[0]],e=>e.pop()]){const copy=JSON.parse(JSON.stringify(entries));alter(copy);assert.equal((await A.verify(copy,head)).ok,false);}});
await test('full animated run logs decisions, all candidates, reassignment and stock changes',async()=>{const s=C.createState(config,scene.nodes),anim=C.createAnimation(s),log=A.create(),o=A.observer(s,log);C.startSimulation(s);for(let i=0;s.status==='running'&&i<3000;i++)o.advance(anim,1/60);const entries=await log.export();assert.equal(s.deliveredCount,13);assert.equal(s.underResourcedCount,2);for(const kind of ['dispatch','arrival','pickup','hospital_select','delivery','reassignment','resolved'])assert(entries.some(e=>e.data.kind===kind),kind);const choices=entries.filter(e=>e.data.kind==='hospital_select');assert.equal(choices.length,7);for(const e of choices){assert.equal(e.data.details.candidates.length,4);assert(e.data.text.includes('eligible')||e.data.text.includes('insufficient'));}const deliveries=entries.filter(e=>e.data.kind==='delivery');assert.equal(deliveries.length,7);assert(deliveries.every(e=>e.data.text.includes(' → ')));assert((await log.verify()).ok);console.log(`  ${entries.length} chained entries; 13 delivered; 2 under-resourced`);});
await test('minute snapshots continue without decisions while vehicles are stuck',async()=>{const s=C.createState(config,scene.nodes);s.roads.forEach(r=>r.blockage=2);const log=A.create(),o=A.observer(s,log),anim=C.createAnimation(s);C.startSimulation(s);o.advance(anim,0);o.advance(anim,125);const e=await log.export(),snaps=e.filter(e=>e.data.kind==='snapshot');assert.deepEqual(Array.from(snaps,x=>x.data.simTime),['01:00','02:00']);assert(snaps.every(e=>e.data.text.includes('A4 stuck')&&e.data.text.includes('fracture: 4')));assert((await log.verify()).ok);});
await test('unreachable hospital reasons and road-restoration reroutes are logged',async()=>{const s=C.createState(config,scene.nodes),log=A.create(),o=A.observer(s,log);C.startSimulation(s);C.tick(s);C.tick(s);for(const r of s.roads)if(r.from.startsWith('H')||r.to.startsWith('H'))r.blockage=2;C.tick(s);o.drain();let entries=await log.export();assert(entries.filter(e=>e.data.kind==='hospital_select').every(e=>e.data.details.candidates.every(c=>!c.reachable)));const s2=C.createState(config,scene.nodes),log2=A.create(),o2=A.observer(s2,log2);s2.roads.forEach(r=>r.blockage=2);C.startSimulation(s2);C.tick(s2);s2.roads.forEach(r=>r.blockage=0);C.tick(s2);o2.drain();entries=await log2.export();assert.equal(entries.filter(e=>e.data.kind==='reroute').length,4);});
await test('edge-bound glyphs: co-located offsets are perpendicular and capped at 6px',()=>{const items=config.fleet.bases.map((_,i)=>({id:'A'+(i+1),position:[50,0],from:[0,0],to:[100,0],progress:.5,active:true})),boxes=L.place(items);for(const b of boxes){assert.equal(b.point[0],50);assert(Math.abs(b.point[1])<=6);}assert(!html.includes('badge-connector'));assert(!html.includes('data-badge-destination'));});
console.log(`${passed}/${passed} Phase 4.5 and glyph tests passed.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
