const fs=require('fs'),vm=require('vm');
const src=require('./helpers/load-app.cjs')(),ids={},all=[];
function matches(e,s){if(s[0]==='#')return e.attrs.id===s.slice(1);if(s[0]==='.')return (e.attrs.class||'').split(' ').includes(s.slice(1));if(s[0]==='['){const m=s.match(/^\[([^=\]]+)(?:="([^"]*)")?\]$/);return m&&(m[2]===undefined?m[1] in e.attrs:e.attrs[m[1]]===m[2]);}return e.tag===s;}
class El{constructor(tag){this.tag=tag;this.attrs={};this.children=[];this.dataset={};this.events={};this.textContent='';this.firstChild={textContent:''};all.push(this);this.classList={toggle:(c,b)=>{const a=new Set((this.attrs.class||'').split(' ').filter(Boolean));b?a.add(c):a.delete(c);this.attrs.class=[...a].join(' ');}};}
 replaceChildren(...items){this.children=[];this.append(...items);}set className(c){this.attrs.class=c;}setAttribute(k,v){this.attrs[k]=String(v);if(k==='id')ids[v]=this;}appendChild(e){this.children.push(e);return e;}append(...items){items.forEach(e=>this.appendChild(e));}addEventListener(k,f){this.events[k]=f;}
 querySelector(s){const bits=s.split(' ');for(const c of this.children){if(matches(c,bits[0])){if(bits.length===1)return c;const r=c.querySelector(bits.slice(1).join(' '));if(r)return r;}const r=c.querySelector(s);if(r)return r;}return null;}}
for(const id of ['scenario','summary','roads','nodes','facilities','vehicles','road-status','reset','dev-run','run-note','decision-log','verify-result','verify-log','audit-dev','tamper-log','fleet-status','playback-speed','playback-note','scenario-help']){ids[id]=new El('g');ids[id].setAttribute('id',id);}const stateEl=new El('div');stateEl.className='state';
const document={getElementById:id=>ids[id],createElementNS:(_,t)=>new El(t),createElement:t=>new El(t),createTextNode:t=>{const e=new El("span");e.textContent=t;return e;},querySelector:s=>{const parts=s.split(' ');for(const e of all)if(matches(e,parts[0])){if(parts.length===1)return e;const r=e.querySelector(parts.slice(1).join(' '));if(r)return r;}return null;}};
const ctx=vm.createContext({document,location:{hash:""},crypto:require("node:crypto").webcrypto,TextEncoder,requestAnimationFrame(){}});for(const m of src.matchAll(/<script(?: id="[^"]+")?>([\s\S]*?)<\/script>/g))vm.runInContext(m[1],ctx);

const assert=require('node:assert/strict');
(async()=>{
assert.equal(vm.runInContext('simulation.status',ctx),'idle');assert.equal(ids['dev-run'].textContent,'Start Simulation');assert.equal(vm.runInContext('playback.rate',ctx),1);console.log('PASS idle gating, start label and Normal 1x default');
ids['dev-run'].events.click();assert.equal(ids['dev-run'].textContent,'Running');assert.equal(ids['dev-run'].disabled,true);assert(ids['scenario-help'].textContent.includes('during'));console.log('PASS start action and running instructions');
vm.runInContext("for(const r of roads)ResqnetCore.setRoadBlockage(animation,r.id,2);playback.advance(2);renderLiveState()",ctx);assert(ids['fleet-status'].children.some(p=>p.textContent.includes('Holding')));assert.equal(vm.runInContext('simulation.status',ctx),'running');console.log('PASS disconnected roads explain holding without false completion');
ids.reset.events.click();vm.runInContext("for(let i=0;i<60000&&simulation.status==='running';i++)playback.advance(1/60);renderLiveState()",ctx);await vm.runInContext('decisionLog.flush()',ctx);assert.equal(vm.runInContext('simulation.status',ctx),'resolved');assert(ids['run-note'].textContent.includes('Delivered 13/13'));assert(ids['run-note'].textContent.includes('Delivery trips 7'));assert(ids['run-note'].textContent.includes('Elapsed '));assert(ids['run-note'].textContent.includes('Under-resourced '));assert.equal(ids['dev-run'].textContent,'Completed');console.log('PASS road recovery and complete summary: '+ids['run-note'].textContent);
await ids['verify-log'].events.click();assert(ids['verify-result'].textContent.includes('chain intact'));await ids['tamper-log'].events.click();await ids['verify-log'].events.click();assert(ids['verify-result'].textContent.includes('2'));assert(/recorded/i.test(ids['verify-result'].textContent));assert(/recomputed/i.test(ids['verify-result'].textContent));console.log('PASS real intact and corrupt log button handlers retain forensic mismatch');
console.log('5/5 Phase 6 DOM-handler checks passed (no browser layout claims).');
})().catch(e=>{console.error(e);process.exitCode=1;});
