import { useEffect, useState } from 'react';
import { useSimulation } from './SimulationContext';
import { SimulationMap } from './SimulationMap';
import { api } from './api';
import type { ScenarioId } from './types';
const display = (items: string[]) => items.length ? items.join(', ') : 'None specified';
const categories = { government: 'Government', authorized_private: 'Authorized private', non_authorized_private: 'Non-authorized private' };
export default function App() {
  const { state, scenarios, busy, error, notice, refresh, reset, start, step } = useSimulation();
  const [selected, setSelected] = useState<ScenarioId>('flood');
  const [ledgerStatus, setLedgerStatus] = useState('Not checked');
  useEffect(() => { if (state) setSelected(state.scenario_id); }, [state?.scenario_id]);
  return <div className="app-shell">
    <header className="topbar"><a href="#" className="brand"><span className="brand-mark">R<span>+</span></span><span>RESQNET<small>DISASTER RESPONSE LAB</small></span></a><div className="topbar-status"><span className="status-dot"/>SPRINT 02 <span className="divider">/</span> ALLOCATION</div></header>
    <main className="max-w-[1440px] mx-auto px-5 md:px-10 py-8">
      <div className="intro"><div><p className="eyebrow">DJSCE ELEVATE 1.0 · EL-02</p><h1>Simulation overview</h1><p className="subtitle">A shared starting point for patients, fleet and hospital resources.</p></div><span className="simulation-label">SYNTHETIC DATA ONLY</span></div>
      <section className="controls" aria-label="Simulation controls"><div className="scenario-control"><label htmlFor="scenario">Predefined scenario</label><select id="scenario" value={selected} disabled={busy || !scenarios.length} onChange={e=>setSelected(e.target.value as ScenarioId)}>{scenarios.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></div><p>{state?.run_status === 'allocated' ? `Run ${state.run_id} · ${state.clock_status} · ${state.sim_time} synthetic min` : 'Select a scenario, then start allocation when ready.'}</p><button className="secondary" onClick={()=>void refresh()} disabled={busy}>Refresh</button><button className="secondary" onClick={()=>void reset(selected)} disabled={busy || !state}>Reset simulation</button><button onClick={()=>void start()} disabled={busy || !state || state.run_status === 'allocated'}>{busy ? 'Working…' : 'Start allocation'}</button><button className="secondary" onClick={()=>void step()} disabled={busy || !state || state.run_status !== 'allocated' || state.clock_status === 'complete'}>Advance 1 min</button></section>
      {error && <div className="error" role="alert">{error} {state && 'Displayed data may be out of date.'} <button className="secondary" disabled={busy} onClick={()=>void refresh()}>Retry</button></div>}
      <div role="status" className="notice">{notice}</div>
      {!state && !error && <p role="status">Loading simulation from FastAPI…</p>}
      {state && <>
        <div className="stats grid grid-cols-2 lg:grid-cols-4 gap-4">
          {[['Patients',state.patients.length,'All awaiting allocation'],['Ambulances',state.ambulances.length,`${state.ambulances.filter(a=>a.status==='available').length} marked available`],['Hospitals',state.hospitals.length,`${state.hospitals.reduce((sum,h)=>sum+h.beds_available,0)} available general beds`],['Road links',state.roads.length,`${state.roads.filter(r=>r.blocked).length} blocked in this scenario`]].map(([label,value,detail])=><article key={label} className="stat"><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>)}
        </div>
        {state.run_status === 'allocated' && <section className="stats grid grid-cols-2 lg:grid-cols-4 gap-4" aria-label="Live metrics"><article className="stat"><p>Delivered</p><strong>{state.metrics.delivered}</strong><small>individual patient records</small></article><article className="stat"><p>Active trips</p><strong>{state.metrics.active_trips}</strong><small>vehicles moving or loading</small></article><article className="stat"><p>Waiting</p><strong>{state.metrics.waiting}</strong><small>with persisted reasons</small></article><article className="stat"><p>Ledger events</p><strong>{state.metrics.ledger_events}</strong><small>hash chained history</small></article></section>}
        <section className="panel map-panel"><div className="panel-heading"><div><p className="eyebrow">SCENARIO NETWORK</p><h2>{state.title}</h2></div><span className="revision" data-testid="revision">Revision {state.revision}</span></div><div className="map-layout"><div className="map-wrap"><SimulationMap state={state}/><div className="map-note">Schematic coordinates · no real-world map tiles</div></div><aside className="map-sidebar"><h3>Scenario brief</h3><p>{state.description}</p><h3>Network legend</h3><ul className="legend"><li><i className="dot patient"/>Patient pickup</li><li><i className="dot ambulance"/>Ambulance</li><li><i className="dot hospital"/>Hospital</li><li><i className="line"/>Open road</li><li><i className="line blocked"/>Blocked road</li><li><i className="zone"/>Hazard zone</li></ul><div className="scope-note"><strong>Foundation only</strong><p>Resources are static. Allocation, grouping, movement and audit services belong to later sprints.</p></div></aside></div></section>
        <section className="panel" aria-labelledby="patients-heading"><div className="panel-heading"><h2 id="patients-heading">Patients <span>{state.patients.length}</span></h2><small>Individual synthetic records</small></div><div className="table-wrap"><table><thead><tr><th>Patient / location</th><th>Severity</th><th>Position</th><th>Declared requirements</th><th>Status</th></tr></thead><tbody>{state.patients.map(p=><tr key={p.id}><td><strong>{p.id}</strong><small>{p.node_id} · {p.incident_id}</small></td><td><span className={`badge ${p.severity}`}>{p.severity}</span></td><td>{p.transport_position}</td><td>{display(p.required_capabilities)}<small>Equipment: {display(p.required_equipment)}<br/>Crew: {display(p.required_crew_roles)}<br/>Facility: {display(p.required_facilities)} · Compatibility: {p.clinical_compatibility_group}</small></td><td>{p.status}</td></tr>)}</tbody></table></div></section>
        <section className="panel" aria-labelledby="fleet-heading"><div className="panel-heading"><h2 id="fleet-heading">Ambulance fleet <span>{state.ambulances.length}</span></h2><small>Capacity comes from individual configuration</small></div><div className="fleet-grid grid md:grid-cols-2 xl:grid-cols-4 gap-4">{state.ambulances.map(a=><article key={a.id} className="vehicle-card"><div className="vehicle-title"><strong>{a.id}</strong><span className={`badge ${a.status==='available'?'stable':'muted'}`}>{a.status}</span></div><h3>{state.ambulance_types.find(t=>t.id===a.type_id)?.label}</h3><p>{a.vehicle_class} · {a.node_id} · home {a.home_node_id}</p><dl><dt>Approved positions</dt><dd>{a.approved_stretcher_positions} stretcher / {a.approved_seated_positions} seated</dd><dt>Occupied positions</dt><dd>{a.occupied_stretcher_positions} stretcher / {a.occupied_seated_positions} seated</dd><dt>Dimensions (L × W × H)</dt><dd>{a.length_m} × {a.width_m} × {a.height_m} m</dd><dt>Declared capabilities</dt><dd>{display(a.declared_capabilities)}</dd><dt>Equipment inventory</dt><dd>{Object.entries(a.equipment).map(([k,v])=>`${k} × ${v}`).join(', ') || 'None'}</dd><dt>Crew availability</dt><dd>{a.crew.map(c=><div key={c.id}>{c.role}: {c.available?'available':'unavailable'}</div>)}</dd></dl><small>{a.configuration_source}</small></article>)}</div></section>
        <section className="panel" aria-labelledby="hospitals-heading"><div className="panel-heading"><h2 id="hospitals-heading">Hospitals <span>{state.hospitals.length}</span></h2><small>Authorization is a simulation field, not a payment guarantee</small></div><div className="table-wrap"><table><thead><tr><th>Hospital</th><th>Category</th><th>General beds</th><th>ICU places</th><th>Facilities / authorization</th></tr></thead><tbody>{state.hospitals.map(h=><tr key={h.id}><td><strong>{h.label}</strong><small>{h.id} · {h.node_id}</small></td><td>{categories[h.category]}</td><td>{h.beds_available} / {h.beds_total} available</td><td>{h.icu_available} / {h.icu_total} available</td><td>{display(h.facilities)}<small>{h.authorization_reference || 'No private authorization reference'}</small></td></tr>)}</tbody></table></div></section>
        <section className="panel" aria-labelledby="roads-heading"><div className="panel-heading"><h2 id="roads-heading">Road network <span>{state.roads.length}</span></h2><small>Undirected links · explicit restrictions</small></div><div className="table-wrap"><table><thead><tr><th>Road</th><th>Distance / time</th><th>Width / height limit</th><th>Allowed vehicle classes</th><th>Road condition</th></tr></thead><tbody>{state.roads.map(r=><tr key={r.id}><td><strong>{r.id}</strong><small>{r.source} ↔ {r.target}</small></td><td>{r.distance_km} km / {r.travel_time_min} min</td><td>{r.max_width_m} m / {r.max_height_m} m</td><td>{r.allowed_vehicle_classes.join(', ')}</td><td><span className={`badge ${r.blocked?'critical':'stable'}`}>{r.blocked?'Blocked':'Open'}</span><small>{r.hazard_zone_id ? `Hazard ${r.hazard_zone_id} · ` : ''}{r.restriction_note}</small></td></tr>)}</tbody></table></div></section>
        {state.run_status === 'allocated' && <section className="panel" aria-labelledby="allocation-heading"><div className="panel-heading"><h2 id="allocation-heading">Allocation decisions <span>{state.allocations.length}</span></h2><small>Feasibility and reservation results</small></div><div className="table-wrap"><table><thead><tr><th>Patient</th><th>Result</th><th>Ambulance</th><th>Hospital</th><th>Travel</th><th>Decision factors</th></tr></thead><tbody>{state.allocations.map(a=><tr key={a.id}><td><strong>{a.patient_id}</strong></td><td><span className={`badge ${a.status === 'assigned' ? 'stable' : 'critical'}`}>{a.status}</span></td><td>{a.ambulance_id ?? '—'}</td><td>{a.hospital_id ?? '—'}</td><td>{a.status === 'assigned' ? `${a.travel_time_min} min` : '—'}</td><td>{a.status === 'waiting' ? a.waiting_reason : <small>Pickup: {a.pickup_path.join(' → ')}<br/>Delivery: {a.delivery_path.join(' → ')}</small>}</td></tr>)}</tbody></table></div></section>}
        {state.run_status === 'allocated' && <section className="panel" aria-labelledby="trips-heading"><div className="panel-heading"><h2 id="trips-heading">Live trips <span>{state.trips.length}</span></h2><small>Authoritative server clock · WebSocket updates</small></div><div className="table-wrap"><table><thead><tr><th>Trip</th><th>Vehicle</th><th>Patients</th><th>Phase</th><th>Position</th><th>Status</th></tr></thead><tbody>{state.trips.map(t=><tr key={t.id}><td><strong>{t.id}</strong></td><td>{t.ambulance_id}</td><td>{t.patient_ids.join(', ')}</td><td>{t.phase}</td><td>{t.current_node}</td><td><span className={`badge ${t.status === 'delivered' ? 'stable' : t.status === 'blocked' ? 'critical' : 'urgent'}`}>{t.status}</span></td></tr>)}</tbody></table></div></section>}
        {state.run_status === 'allocated' && <section className="panel" aria-labelledby="ledger-heading"><div className="panel-heading"><h2 id="ledger-heading">Transparent event chain</h2><button className="secondary" onClick={()=>void api.verifyLedger().then(result=>setLedgerStatus(result.valid ? `Valid · ${result.checked} events` : `Invalid at event ${result.first_failure ?? '?'}`)).catch(()=>setLedgerStatus('Verification request failed'))}>Verify SHA-256 chain</button></div><p className="scope-note">{ledgerStatus}. Events are synthetic and retained for audit review.</p></section>}
      </>}
      <footer>RESQNET / MVP · Fictional training simulation. No real patient data or operational dispatch.</footer>
    </main>
  </div>;
}
