import { useEffect, useState } from 'react';
import { useSimulation } from './SimulationContext';
import { SimulationMap } from './SimulationMap';
import type { ScenarioId } from './types';
const display = (items: string[]) => items.length ? items.join(', ') : 'None specified';
const categories = { government: 'Government', authorized_private: 'Authorized private', non_authorized_private: 'Non-authorized private' };
export default function App() {
  const { state, scenarios, busy, error, notice, refresh, reset } = useSimulation();
  const [selected, setSelected] = useState<ScenarioId>('flood');
  useEffect(() => { if (state) setSelected(state.scenario_id); }, [state?.scenario_id]);
  return <div className="app-shell">
    <header className="topbar"><a href="#" className="brand"><span className="brand-mark">R<span>+</span></span><span>RESQNET<small>DISASTER RESPONSE LAB</small></span></a><div className="topbar-status"><span className="status-dot"/>SPRINT 01 <span className="divider">/</span> FOUNDATION</div></header>
    <main className="max-w-[1440px] mx-auto px-5 md:px-10 py-8">
      <div className="intro"><div><p className="eyebrow">DJSCE ELEVATE 1.0 · EL-02</p><h1>Simulation overview</h1><p className="subtitle">A shared starting point for patients, fleet and hospital resources.</p></div><span className="simulation-label">SYNTHETIC DATA ONLY</span></div>
      <section className="controls" aria-label="Simulation controls"><div className="scenario-control"><label htmlFor="scenario">Predefined scenario</label><select id="scenario" value={selected} disabled={busy || !scenarios.length} onChange={e=>setSelected(e.target.value as ScenarioId)}>{scenarios.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></div><p>Reset restores all resources to the selected scenario’s initial state.</p><button className="secondary" onClick={()=>void refresh()} disabled={busy}>Refresh</button><button onClick={()=>void reset(selected)} disabled={busy || !state}>{busy ? 'Loading…' : 'Reset simulation'}</button></section>
      {error && <div className="error" role="alert">{error} {state && 'Displayed data may be out of date.'} <button className="secondary" disabled={busy} onClick={()=>void refresh()}>Retry</button></div>}
      <div role="status" className="notice">{notice}</div>
      {!state && !error && <p role="status">Loading simulation from FastAPI…</p>}
      {state && <>
        <div className="stats grid grid-cols-2 lg:grid-cols-4 gap-4">
          {[['Patients',state.patients.length,'All awaiting allocation'],['Ambulances',state.ambulances.length,`${state.ambulances.filter(a=>a.status==='available').length} marked available`],['Hospitals',state.hospitals.length,`${state.hospitals.reduce((sum,h)=>sum+h.beds_available,0)} available general beds`],['Road links',state.roads.length,`${state.roads.filter(r=>r.blocked).length} blocked in this scenario`]].map(([label,value,detail])=><article key={label} className="stat"><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>)}
        </div>
        <section className="panel map-panel"><div className="panel-heading"><div><p className="eyebrow">SCENARIO NETWORK</p><h2>{state.title}</h2></div><span className="revision" data-testid="revision">Revision {state.revision}</span></div><div className="map-layout"><div className="map-wrap"><SimulationMap state={state}/><div className="map-note">Schematic coordinates · no real-world map tiles</div></div><aside className="map-sidebar"><h3>Scenario brief</h3><p>{state.description}</p><h3>Network legend</h3><ul className="legend"><li><i className="dot patient"/>Patient pickup</li><li><i className="dot ambulance"/>Ambulance</li><li><i className="dot hospital"/>Hospital</li><li><i className="line"/>Open road</li><li><i className="line blocked"/>Blocked road</li><li><i className="zone"/>Hazard zone</li></ul><div className="scope-note"><strong>Foundation only</strong><p>Resources are static. Allocation, grouping, movement and audit services belong to later sprints.</p></div></aside></div></section>
        <section className="panel" aria-labelledby="patients-heading"><div className="panel-heading"><h2 id="patients-heading">Patients <span>{state.patients.length}</span></h2><small>Individual synthetic records</small></div><div className="table-wrap"><table><thead><tr><th>Patient / location</th><th>Severity</th><th>Position</th><th>Declared requirements</th><th>Status</th></tr></thead><tbody>{state.patients.map(p=><tr key={p.id}><td><strong>{p.id}</strong><small>{p.node_id} · {p.incident_id}</small></td><td><span className={`badge ${p.severity}`}>{p.severity}</span></td><td>{p.transport_position}</td><td>{display(p.required_capabilities)}<small>Equipment: {display(p.required_equipment)}<br/>Crew: {display(p.required_crew_roles)}<br/>Facility: {display(p.required_facilities)} · Compatibility: {p.clinical_compatibility_group}</small></td><td>{p.status}</td></tr>)}</tbody></table></div></section>
        <section className="panel" aria-labelledby="fleet-heading"><div className="panel-heading"><h2 id="fleet-heading">Ambulance fleet <span>{state.ambulances.length}</span></h2><small>Capacity comes from individual configuration</small></div><div className="fleet-grid grid md:grid-cols-2 xl:grid-cols-4 gap-4">{state.ambulances.map(a=><article key={a.id} className="vehicle-card"><div className="vehicle-title"><strong>{a.id}</strong><span className={`badge ${a.status==='available'?'stable':'muted'}`}>{a.status}</span></div><h3>{state.ambulance_types.find(t=>t.id===a.type_id)?.label}</h3><p>{a.vehicle_class} · {a.node_id} · home {a.home_node_id}</p><dl><dt>Approved positions</dt><dd>{a.approved_stretcher_positions} stretcher / {a.approved_seated_positions} seated</dd><dt>Occupied positions</dt><dd>{a.occupied_stretcher_positions} stretcher / {a.occupied_seated_positions} seated</dd><dt>Dimensions (L × W × H)</dt><dd>{a.length_m} × {a.width_m} × {a.height_m} m</dd><dt>Declared capabilities</dt><dd>{display(a.declared_capabilities)}</dd><dt>Equipment inventory</dt><dd>{Object.entries(a.equipment).map(([k,v])=>`${k} × ${v}`).join(', ') || 'None'}</dd><dt>Crew availability</dt><dd>{a.crew.map(c=><div key={c.id}>{c.role}: {c.available?'available':'unavailable'}</div>)}</dd></dl><small>{a.configuration_source}</small></article>)}</div></section>
        <section className="panel" aria-labelledby="hospitals-heading"><div className="panel-heading"><h2 id="hospitals-heading">Hospitals <span>{state.hospitals.length}</span></h2><small>Authorization is a simulation field, not a payment guarantee</small></div><div className="table-wrap"><table><thead><tr><th>Hospital</th><th>Category</th><th>General beds</th><th>ICU places</th><th>Facilities / authorization</th></tr></thead><tbody>{state.hospitals.map(h=><tr key={h.id}><td><strong>{h.label}</strong><small>{h.id} · {h.node_id}</small></td><td>{categories[h.category]}</td><td>{h.beds_available} / {h.beds_total} available</td><td>{h.icu_available} / {h.icu_total} available</td><td>{display(h.facilities)}<small>{h.authorization_reference || 'No private authorization reference'}</small></td></tr>)}</tbody></table></div></section>
        <section className="panel" aria-labelledby="roads-heading"><div className="panel-heading"><h2 id="roads-heading">Road network <span>{state.roads.length}</span></h2><small>Undirected links · explicit restrictions</small></div><div className="table-wrap"><table><thead><tr><th>Road</th><th>Distance / time</th><th>Width / height limit</th><th>Allowed vehicle classes</th><th>Road condition</th></tr></thead><tbody>{state.roads.map(r=><tr key={r.id}><td><strong>{r.id}</strong><small>{r.source} ↔ {r.target}</small></td><td>{r.distance_km} km / {r.travel_time_min} min</td><td>{r.max_width_m} m / {r.max_height_m} m</td><td>{r.allowed_vehicle_classes.join(', ')}</td><td><span className={`badge ${r.blocked?'critical':'stable'}`}>{r.blocked?'Blocked':'Open'}</span><small>{r.hazard_zone_id ? `Hazard ${r.hazard_zone_id} · ` : ''}{r.restriction_note}</small></td></tr>)}</tbody></table></div></section>
      </>}
      <footer>RESQNET / Sprint 1 · Fictional training simulation. No real patient data or operational dispatch.</footer>
    </main>
  </div>;
}
