// Mirrors the local MVP API. The generated OpenAPI contract lives in docs/openapi.json.
export type ScenarioId = 'flood' | 'building_collapse' | 'industrial_gas_leak';
export interface ScenarioSummary { id: ScenarioId; title: string; description: string }
export interface RoadNode { id: string; label: string; x: number; y: number }
export interface HazardZone { id: string; kind: string; label: string; active: boolean; polygon: [number, number][]; note: string }
export interface Road { id: string; source: string; target: string; distance_km: number; travel_time_min: number; max_width_m: number; max_height_m: number; allowed_vehicle_classes: string[]; blocked: boolean; hazard_zone_id: string | null; restriction_note: string }
export interface CatalogEntry { id: string; label: string; description: string }
export interface Patient { id: string; label: string; incident_id: string; node_id: string; severity: 'critical' | 'urgent' | 'stable'; transport_position: 'stretcher' | 'seated'; required_capabilities: string[]; required_equipment: string[]; required_crew_roles: string[]; required_facilities: string[]; clinical_compatibility_group: string; required_hospital_place: 'general' | 'icu'; status: 'waiting' }
export interface Ambulance { id: string; label: string; type_id: string; node_id: string; home_node_id: string; vehicle_class: string; length_m: number; width_m: number; height_m: number; approved_stretcher_positions: number; approved_seated_positions: number; occupied_stretcher_positions: number; occupied_seated_positions: number; equipment: Record<string, number>; crew: { id: string; role: string; available: boolean }[]; declared_capabilities: string[]; status: 'available' | 'unavailable'; configuration_source: string }
export interface Hospital { id: string; label: string; node_id: string; category: 'government' | 'authorized_private' | 'non_authorized_private'; authorization_reference: string; beds_total: number; beds_available: number; icu_total: number; icu_available: number; facilities: string[] }
export interface Allocation { id: string; revision: number; patient_id: string; ambulance_id: string | null; hospital_id: string | null; pickup_path: string[]; delivery_path: string[]; travel_time_min: number; factors: Record<string, unknown>; waiting_reason: string | null; status: 'assigned' | 'waiting' }
export interface Reservation { id: string; allocation_id: string; resource_type: string; resource_key: string; quantity: number }
export interface Trip { id: string; allocation_id: string; ambulance_id: string; hospital_id: string; patient_ids: string[]; phase: string; status: 'active' | 'delivered' | 'blocked' | 'idle'; current_node: string; pickup_path: string[]; delivery_path: string[]; route_index: number; distance_km: number; travel_time_min: number; reason: string | null }
export interface SimulationMetrics { patients_total: number; assigned: number; delivered: number; waiting: number; active_trips: number; ledger_events: number }
export interface SimulationState { schema_version: number; scenario_id: ScenarioId; title: string; description: string; revision: number; synthetic: true; run_status: 'idle' | 'allocated'; clock_status: 'idle' | 'running' | 'paused' | 'complete'; run_id: string; sim_time: number; nodes: RoadNode[]; hazard_zones: HazardZone[]; roads: Road[]; ambulance_types: CatalogEntry[]; equipment_types: CatalogEntry[]; patients: Patient[]; ambulances: Ambulance[]; hospitals: Hospital[]; allocations: Allocation[]; reservations: Reservation[]; trips: Trip[]; ledger: Record<string, unknown>[]; metrics: SimulationMetrics }
